version: "3.8"
services:
  database:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27017:27017
    networks:
      - soa-team-e-network

networks:
  soa-team-e-network:
    driver: bridge