version: "3.8"
services:
  database:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27017:27017
    networks:
      - soa-team-e-network




  life-support-service:
    image: life-support-service
    restart: always
    ports:
      - 4304:4304
    environment:
      - APP_PORT=4304
      - APP_NAME=life-support-service
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=life-support-db
      - SWAGGERUI_PATH=doc/life-support
      - SWAGGERUI_TITLE=Life Support Micro-Service
      - SWAGGERUI_DESCRIPTION=Destiné à la surveillance des conditions des systèmes de support des modules habités
      - MODULE_LIFE_SERVICE_URL_WITH_PORT=module-life-service:4303
    depends_on:
      - database
    networks:
      - soa-team-e-network


  gateway:
    image: gateway
    restart: always
    ports:
      - 9500:3000
    environment:
      - APP_PORT=3000
      - LIFE_SUPPORT_SERVICE=life-support-service
      - MODULE_LIFE_SERVICE=module-life-service
      - NEEDS_CONTROL_SERVICE=needs-control-service
      - RESUPPLY_CONTROL_SERVICE=resupply-service
      - LIFE_SUPPORT_SERVICE_URL_WITH_PORT=life-support-service:4304
      - MODULE_LIFE_SERVICE_URL_WITH_PORT=module-life-service:4303
      - NEEDS_CONTROL_SERVICE_URL_WITH_PORT=needs-control-service:4302
      - RESUPPLY_CONTROL_SERVICE_URL_WITH_PORT=resupply-service:4301
    networks:
      - soa-team-e-network

networks:
  soa-team-e-network:
    driver: bridge
