version: "3"

services:
  gateway:
    image: "soa-team-e/gateway"
    restart: always
    command: npm run start
    ports:
      - 9500:3000
    environment:
      - APP_PORT=3000
      - LIFE_SUPPORT_SERVICE=life-support-service
      - MODULE_LIFE_SERVICE=module-life-service
      - NEEDS_CONTROL_SERVICE=needs-control-service
      - RESUPPLY_CONTROL_SERVICE=resupply-service
      - LIFE_SUPPORT_SERVICE_URL_WITH_PORT=life-support-service:4204
      - MODULE_LIFE_SERVICE_URL_WITH_PORT=module-life-service:4203
      - NEEDS_CONTROL_SERVICE_URL_WITH_PORT=needs-control-service:4202
      - RESUPPLY_CONTROL_SERVICE_URL_WITH_PORT=resupply-service:4201
    networks:
      - soa-team-e-network
    depends_on:
      - life-support-service
      - module-life-service
      - needs-control-service
      - resupply-service
networks:
  soa-team-e-network:
    driver: bridge
