version: "3.9"
services:
  gateway-development:
    build:
      context: .
      target: docker-development
    ports:
      - ${APP_PORT}:${APP_PORT}             # APP_PORT from the file .env
      - '9233:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - soa-team-e-network-development
networks:
  soa-team-e-network-development:
    driver: bridge
