version: "3"

services:
  gateway:
    image: "soa-team-e/gateway"
    restart: always
    command: npm run start
    ports:
      - 9500:${APP_PORT}
    env_file:
      - .env.docker
    networks:
      - soa-team-e-network
networks:
  soa-team-e-network:
    driver: bridge
