version: "3"

services:
  needs-control-service:
    image: "soa-team-e/needs-control-service"
    restart: always
    command: npm run start
    ports:
      - 4302:${APP_PORT}
    env_file:
      - .env.production
    depends_on:
      - mongo_db_needs_control
    networks:
      - soa-team-e-network
  mongo_db_needs_control:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27019:27017
    networks:
      - soa-team-e-network
networks:
  soa-team-e-network:
    driver: bridge
