version: "3"

services:
  life-support-service:
    image: "soa-team-e/life-support-service"
    restart: always
    command: npm run start
    ports:
      - 4304:${APP_PORT}
    env_file:
      - .env.production
    depends_on:
      - mongo_db_life_support
    networks:
      - soa-team-e-network
  mongo_db_life_support:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27017:27017
    networks:
      - soa-team-e-network
networks:
  soa-team-e-network:
    driver: bridge
