name: "Verify Build"

on: [push, pull_request]

jobs:
  build-gateway:
    runs-on: ubuntu-latest
    container:
      image: "node:16.16.0-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install --prefix gateway/
      - run: npm run build --prefix gateway/

  build-survival-control-service:
    runs-on: ubuntu-latest
    container:
      image: "node:16.16.0-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install --prefix survival-control-service/
      - run: npm run build --prefix survival-control-service/

  build-module-life-service:
    runs-on: ubuntu-latest
    container:
      image: "node:16.16.0-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install --prefix module-life-service/
      - run: npm run build --prefix module-life-service/

  build-needs-control-service:
    runs-on: ubuntu-latest
    container:
      image: "node:16.16.0-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install --prefix needs-control-service/
      - run: npm run build --prefix needs-control-service/

  build-resupply-service:
    runs-on: ubuntu-latest
    container:
      image: "node:16.16.0-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install --prefix rotation-mission-service/
      - run: npm run build --prefix rotation-mission-service/
